# =================================
# = Spring
# =================================
spring:
  datasource:

    url: jdbc:mysql://realmeet-db.cm4aga0zdanl.us-east-1.rds.amazonaws.com:3306/realmeet?&serverTimezone=UTC&useSSL=false
    username: admin